resources:
  - name: petclinic_repo
    type: GitRepo
    configuration:
      path: mjmckay/workshop-jfrog-linkerd
      gitProvider: MyRepo
      branches:
        include: main
      buildOn:
        commit:                false
        pullRequestCreate:     false
        releaseCreate:  true

pipelines:
  - name: petclinic_deploy
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: mjmckay.jfrog.io/default-docker-virtual/alpine/k8slinkerd
            tag: v0.1.0
            autoPull: true
            registry: MyArtifactory
            sourceRepository: default-docker-virtual
    steps:
      - name: kubernetes_deploy
        type: Bash
        configuration:
          integrations:
            - name: MyCluster
          inputResources:
            - name: petclinic_repo
        execution:
          onExecute:
            - cd $res_petclinic_repo_resourcePath/spring-petclinic-cloud
            - export REPOSITORY_PREFIX=springcommunity
            - mkdir $HOME/.kube
            - echo $int_MyCluster_kubeconfig > $HOME/.kube/config
            - cat $HOME/.kube/config
            - kubectl apply -f k8s/init-namespace
            - kubectl apply -f k8s/init-services
            - bash scripts/deployToKubernetes.sh
          onSuccess:
            - echo "Petclinic ${run_number} deployed!"
